### ISSUE TITLE
Array to string conversion

### ISSUE THREAD

**Issue by alinademi** [boospot/boo-settings-helper#3]
There is a PHP notice "Array to string conversion" on these lines.
class-boo-settings-helper.php:943
class-boo-settings-helper.php:564

**Comment by raoabid** [comment]
@alinademi 

can you also share the code you are using to create settings page?
I am using it on multiple projects but haven't got this error.

Need more info to troubleshoot.

_ Rao

**Comment by alinademi** [comment]
@raoabid 
The error is all gone now, and I could not reproduce it again.
It was strange to me as well. That's why I reached out because I have used this class in two more projects and haven't found an issue.
I will keep you updated if it repeats.
Thanks.

**Comment by raoabid** [comment]
@alinademi

Thanks for the update.
Closing this issue for now.

- Rao
